/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model.impl;

import com.liferay.sales.model.CartProductsList;
import com.liferay.sales.service.CartProductsListLocalServiceUtil;

/**
 * The extended model base implementation for the CartProductsList service. Represents a row in the &quot;SalesTaxe_CartProductsList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CartProductsListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CartProductsListImpl
 * @see CartProductsList
 * @generated
 */
public abstract class CartProductsListBaseImpl
	extends CartProductsListModelImpl implements CartProductsList {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cart products list model instance should use the <code>CartProductsList</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CartProductsListLocalServiceUtil.addCartProductsList(this);
		}
		else {
			CartProductsListLocalServiceUtil.updateCartProductsList(this);
		}
	}

}