/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model.impl;

import com.liferay.sales.model.SaleType;
import com.liferay.sales.service.SaleTypeLocalServiceUtil;

/**
 * The extended model base implementation for the SaleType service. Represents a row in the &quot;SalesTaxe_SaleType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SaleTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleTypeImpl
 * @see SaleType
 * @generated
 */
public abstract class SaleTypeBaseImpl
	extends SaleTypeModelImpl implements SaleType {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sale type model instance should use the <code>SaleType</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SaleTypeLocalServiceUtil.addSaleType(this);
		}
		else {
			SaleTypeLocalServiceUtil.updateSaleType(this);
		}
	}

}