/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.sales.model.SaleStock;
import com.liferay.sales.model.SaleStockModel;
import com.liferay.sales.model.SaleStockSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SaleStock service. Represents a row in the &quot;SalesTaxe_SaleStock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SaleStockModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SaleStockImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleStockImpl
 * @generated
 */
@JSON(strict = true)
public class SaleStockModelImpl
	extends BaseModelImpl<SaleStock> implements SaleStockModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sale stock model instance should use the <code>SaleStock</code> interface instead.
	 */
	public static final String TABLE_NAME = "SalesTaxe_SaleStock";

	public static final Object[][] TABLE_COLUMNS = {
		{"StockId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"quantity", Types.INTEGER}, {"typeId", Types.BIGINT},
		{"categoryId", Types.BIGINT}, {"price", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("StockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("price", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SalesTaxe_SaleStock (StockId LONG not null primary key,name VARCHAR(75) null,quantity INTEGER,typeId LONG,categoryId LONG,price DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table SalesTaxe_SaleStock";

	public static final String ORDER_BY_JPQL =
		" ORDER BY saleStock.StockId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SalesTaxe_SaleStock.StockId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STOCKID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SaleStock toModel(SaleStockSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SaleStock model = new SaleStockImpl();

		model.setStockId(soapModel.getStockId());
		model.setName(soapModel.getName());
		model.setQuantity(soapModel.getQuantity());
		model.setTypeId(soapModel.getTypeId());
		model.setCategoryId(soapModel.getCategoryId());
		model.setPrice(soapModel.getPrice());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SaleStock> toModels(SaleStockSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SaleStock> models = new ArrayList<SaleStock>(soapModels.length);

		for (SaleStockSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SaleStockModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _StockId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStockId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _StockId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SaleStock.class;
	}

	@Override
	public String getModelClassName() {
		return SaleStock.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SaleStock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SaleStock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SaleStock, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SaleStock)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SaleStock, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SaleStock, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SaleStock)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SaleStock, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SaleStock, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SaleStock>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SaleStock.class.getClassLoader(), SaleStock.class,
			ModelWrapper.class);

		try {
			Constructor<SaleStock> constructor =
				(Constructor<SaleStock>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SaleStock, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SaleStock, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SaleStock, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SaleStock, Object>>();
		Map<String, BiConsumer<SaleStock, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SaleStock, ?>>();

		attributeGetterFunctions.put("StockId", SaleStock::getStockId);
		attributeSetterBiConsumers.put(
			"StockId", (BiConsumer<SaleStock, Long>)SaleStock::setStockId);
		attributeGetterFunctions.put("name", SaleStock::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<SaleStock, String>)SaleStock::setName);
		attributeGetterFunctions.put("quantity", SaleStock::getQuantity);
		attributeSetterBiConsumers.put(
			"quantity", (BiConsumer<SaleStock, Integer>)SaleStock::setQuantity);
		attributeGetterFunctions.put("typeId", SaleStock::getTypeId);
		attributeSetterBiConsumers.put(
			"typeId", (BiConsumer<SaleStock, Long>)SaleStock::setTypeId);
		attributeGetterFunctions.put("categoryId", SaleStock::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<SaleStock, Long>)SaleStock::setCategoryId);
		attributeGetterFunctions.put("price", SaleStock::getPrice);
		attributeSetterBiConsumers.put(
			"price", (BiConsumer<SaleStock, Double>)SaleStock::setPrice);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getStockId() {
		return _StockId;
	}

	@Override
	public void setStockId(long StockId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StockId = StockId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantity = quantity;
	}

	@JSON
	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeId = typeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTypeId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("typeId"));
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryId = categoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCategoryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("categoryId"));
	}

	@JSON
	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SaleStock.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SaleStock toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SaleStock>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SaleStockImpl saleStockImpl = new SaleStockImpl();

		saleStockImpl.setStockId(getStockId());
		saleStockImpl.setName(getName());
		saleStockImpl.setQuantity(getQuantity());
		saleStockImpl.setTypeId(getTypeId());
		saleStockImpl.setCategoryId(getCategoryId());
		saleStockImpl.setPrice(getPrice());

		saleStockImpl.resetOriginalValues();

		return saleStockImpl;
	}

	@Override
	public int compareTo(SaleStock saleStock) {
		long primaryKey = saleStock.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SaleStock)) {
			return false;
		}

		SaleStock saleStock = (SaleStock)object;

		long primaryKey = saleStock.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SaleStock> toCacheModel() {
		SaleStockCacheModel saleStockCacheModel = new SaleStockCacheModel();

		saleStockCacheModel.StockId = getStockId();

		saleStockCacheModel.name = getName();

		String name = saleStockCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			saleStockCacheModel.name = null;
		}

		saleStockCacheModel.quantity = getQuantity();

		saleStockCacheModel.typeId = getTypeId();

		saleStockCacheModel.categoryId = getCategoryId();

		saleStockCacheModel.price = getPrice();

		return saleStockCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SaleStock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SaleStock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SaleStock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((SaleStock)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SaleStock, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SaleStock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SaleStock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SaleStock)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SaleStock>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _StockId;
	private String _name;
	private int _quantity;
	private long _typeId;
	private long _categoryId;
	private double _price;

	public <T> T getColumnValue(String columnName) {
		Function<SaleStock, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SaleStock)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("StockId", _StockId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("quantity", _quantity);
		_columnOriginalValues.put("typeId", _typeId);
		_columnOriginalValues.put("categoryId", _categoryId);
		_columnOriginalValues.put("price", _price);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("StockId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("quantity", 4L);

		columnBitmasks.put("typeId", 8L);

		columnBitmasks.put("categoryId", 16L);

		columnBitmasks.put("price", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SaleStock _escapedModel;

}