
components:
  schemas:
    Category:
      description: Category
      properties:
        name:
          description: The category name.
          type: string
        id:
          description: The category ID.
          type: integer
        tax:
          description: The tax category.
          format: double
          type: number
      type: object
    Type:
      description: Type
      properties:
        name:
          description: The type name.
          type: string
        id:
          description: The type ID.
          type: integer
        tax:
          description: the type tax.
          format: double
          type: number
      type: object
    Product:
      description: Product
      properties:
        name:
          description: The entity name.
          type: string
        id:
          description: The entity ID.
          type: integer
        category:
          allOf:
            - $ref: "#/components/schemas/Category"
        type:
          allOf:
            - $ref: "#/components/schemas/Type"
        price:
          description: The price product.
          format: double
          type: number
      type: object
    Cart:
      description: Cart
      properties:
        id:
          description: The Cart ID.
          type: integer
        totalValue:
          description: total payment amount.
          format: double
          type: number
        productList:
          type: array
          items:
            type: object
            description: array de produtos
            properties:
              name:
                description: The entity name.
                type: string
              id:
                description: The entity ID.
                type: integer
              category:
                allOf:
                  - $ref: "#/components/schemas/Category"
              type:
                allOf:
                  - $ref: "#/components/schemas/Type"
              price:
                description: The price product.
                format: double
                type: number
      type: object

info:
  description: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "Sale Taxe API"
  version: v1.0
openapi: 3.0.1
paths:
  "/product/all":
    get:
      operationId: getAllProducts
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
                type: array
            application/xml:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
      tags: ["Product"]

  "/product/{productId}":
    get:
      operationId: getProductById
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
            application/xml:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
      tags: ["Product"]

  "/product/create":
    post:
      operationId: creatProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
          application/xml:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
            application/xml:
              schema:
                $ref: "#/components/schemas/Product"
          description: ""
      tags: ["Product"]

  "/product/delete/{productId}":
    delete:
      operationId: deleteProductById
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json: {}
            application/xml: {}
          description: ""
      tags: ["Product"]

  "/category/all":
    get:
      operationId: getAllCategories
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Category"
                type: array
            application/xml:
              schema:
                $ref: "#/components/schemas/Category"
          description: ""
      tags: ["Category"]


  "/category/{categoryName}":
    get:
      operationId: getCategoryByName
      parameters:
        - in: path
          name: categoryName
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
            application/xml:
              schema:
                $ref: "#/components/schemas/Category"
          description: ""
      tags: ["Category"]

  "/category/{categoryId}":
    get:
      operationId: getCategoryById
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
            application/xml:
              schema:
                $ref: "#/components/schemas/Category"
          description: ""
      tags: [ "Category" ]

  "/category/create":
    post:
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
          application/xml:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
            application/xml:
              schema:
                $ref: "#/components/schemas/Category"
          description: ""
      tags: ["Category"]

  "/category/delete/{categoryId}":
    delete:
      operationId: deleteCategoryById
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json: {}
            application/xml: {}
          description: ""
      tags: ["Category"]

  "/type/all":
    get:
      operationId: getAllTypes
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Type"
                type: array
            application/xml:
              schema:
                $ref: "#/components/schemas/Type"
          description: ""
      tags: ["Type"]


  "/type/{typeId}":
    get:
      operationId: getTypeById
      parameters:
        - in: path
          name: typeId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Type"
            application/xml:
              schema:
                $ref: "#/components/schemas/Type"
          description: ""
      tags: ["Type"]

  "/type/create":
    post:
      operationId: createType
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Type"
          application/xml:
            schema:
              $ref: "#/components/schemas/Type"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Type"
            application/xml:
              schema:
                $ref: "#/components/schemas/Type"
          description: ""
      tags: ["Type"]

  "/type/delete/{typeId}":
    delete:
      operationId: deleteTypeById
      parameters:
        - in: path
          name: typeId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json: {}
            application/xml: {}
          description: ""
      tags: ["Type"]
  "/cart/getAll":
    get:
      operationId: getAllCarts
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"

            application/xml:
              schema:
                $ref: "#/components/schemas/Cart"
          description: ""
      tags: ["Cart"]
  "/cart/{cartId}":
    get:
      operationId: getCartById
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
            application/xml:
              schema:
                $ref: "#/components/schemas/Cart"
          description: ""
      tags: ["Cart"]
  "/addProduct/carts/{cartId}/products/{productId}":
    post:
      operationId: addProductToCart
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
        - in: path
          name: productId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
            application/xml:
              schema:
                $ref: "#/components/schemas/Cart"
          description: ""
      tags: ["Cart"]
  "/removeProduct/carts/{cartId}/products/{productId}":
    post:
      operationId: removeProductToCart
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
        - in: path
          name: productId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json: {}
            application/xml: {}
          description: ""
      tags: ["Cart"]

  "/cart/delete/{cartId}":
    delete:
      operationId: deleteCartById
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json: {}
            application/xml: {}
          description: ""
      tags: ["Cart"]