/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SaleType service. Represents a row in the &quot;SalesTaxe_SaleType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.SaleTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.SaleTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleType
 * @generated
 */
@ProviderType
public interface SaleTypeModel extends BaseModel<SaleType> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sale type model instance should use the {@link SaleType} interface instead.
	 */

	/**
	 * Returns the primary key of this sale type.
	 *
	 * @return the primary key of this sale type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sale type.
	 *
	 * @param primaryKey the primary key of this sale type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this sale type.
	 *
	 * @return the type ID of this sale type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this sale type.
	 *
	 * @param typeId the type ID of this sale type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the name of this sale type.
	 *
	 * @return the name of this sale type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sale type.
	 *
	 * @param name the name of this sale type
	 */
	public void setName(String name);

	/**
	 * Returns the tax of this sale type.
	 *
	 * @return the tax of this sale type
	 */
	public double getTax();

	/**
	 * Sets the tax of this sale type.
	 *
	 * @param tax the tax of this sale type
	 */
	public void setTax(double tax);

}