/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CartProductsList service. Represents a row in the &quot;SalesTaxe_CartProductsList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.CartProductsListModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.CartProductsListImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CartProductsList
 * @generated
 */
@ProviderType
public interface CartProductsListModel extends BaseModel<CartProductsList> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cart products list model instance should use the {@link CartProductsList} interface instead.
	 */

	/**
	 * Returns the primary key of this cart products list.
	 *
	 * @return the primary key of this cart products list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cart products list.
	 *
	 * @param primaryKey the primary key of this cart products list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this cart products list.
	 *
	 * @return the product ID of this cart products list
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this cart products list.
	 *
	 * @param productId the product ID of this cart products list
	 */
	public void setProductId(long productId);

	/**
	 * Returns the cart ID of this cart products list.
	 *
	 * @return the cart ID of this cart products list
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this cart products list.
	 *
	 * @param cartId the cart ID of this cart products list
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the quantity of this cart products list.
	 *
	 * @return the quantity of this cart products list
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this cart products list.
	 *
	 * @param quantity the quantity of this cart products list
	 */
	public void setQuantity(int quantity);

}