/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SaleProduct service. Represents a row in the &quot;SalesTaxe_SaleProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.SaleProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.SaleProductImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleProduct
 * @generated
 */
@ProviderType
public interface SaleProductModel extends BaseModel<SaleProduct> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sale product model instance should use the {@link SaleProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this sale product.
	 *
	 * @return the primary key of this sale product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sale product.
	 *
	 * @param primaryKey the primary key of this sale product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this sale product.
	 *
	 * @return the product ID of this sale product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this sale product.
	 *
	 * @param productId the product ID of this sale product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the name of this sale product.
	 *
	 * @return the name of this sale product
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this sale product.
	 *
	 * @param name the name of this sale product
	 */
	public void setName(String name);

	/**
	 * Returns the price of this sale product.
	 *
	 * @return the price of this sale product
	 */
	public double getPrice();

	/**
	 * Sets the price of this sale product.
	 *
	 * @param price the price of this sale product
	 */
	public void setPrice(double price);

	/**
	 * Returns the category ID of this sale product.
	 *
	 * @return the category ID of this sale product
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this sale product.
	 *
	 * @param categoryId the category ID of this sale product
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the type ID of this sale product.
	 *
	 * @return the type ID of this sale product
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this sale product.
	 *
	 * @param typeId the type ID of this sale product
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the quantity of this sale product.
	 *
	 * @return the quantity of this sale product
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this sale product.
	 *
	 * @param quantity the quantity of this sale product
	 */
	public void setQuantity(int quantity);

}