/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SaleStock service. Represents a row in the &quot;SalesTaxe_SaleStock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.SaleStockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.SaleStockImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleStock
 * @generated
 */
@ProviderType
public interface SaleStockModel extends BaseModel<SaleStock> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sale stock model instance should use the {@link SaleStock} interface instead.
	 */

	/**
	 * Returns the primary key of this sale stock.
	 *
	 * @return the primary key of this sale stock
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sale stock.
	 *
	 * @param primaryKey the primary key of this sale stock
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stock ID of this sale stock.
	 *
	 * @return the stock ID of this sale stock
	 */
	public long getStockId();

	/**
	 * Sets the stock ID of this sale stock.
	 *
	 * @param StockId the stock ID of this sale stock
	 */
	public void setStockId(long StockId);

	/**
	 * Returns the quantity of this sale stock.
	 *
	 * @return the quantity of this sale stock
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this sale stock.
	 *
	 * @param quantity the quantity of this sale stock
	 */
	public void setQuantity(int quantity);

}