/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SaleCart service. Represents a row in the &quot;SalesTaxe_SaleCart&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.SaleCartModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.SaleCartImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SaleCart
 * @generated
 */
@ProviderType
public interface SaleCartModel extends BaseModel<SaleCart> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sale cart model instance should use the {@link SaleCart} interface instead.
	 */

	/**
	 * Returns the primary key of this sale cart.
	 *
	 * @return the primary key of this sale cart
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sale cart.
	 *
	 * @param primaryKey the primary key of this sale cart
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cart ID of this sale cart.
	 *
	 * @return the cart ID of this sale cart
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this sale cart.
	 *
	 * @param cartId the cart ID of this sale cart
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the total price of this sale cart.
	 *
	 * @return the total price of this sale cart
	 */
	public double getTotalPrice();

	/**
	 * Sets the total price of this sale cart.
	 *
	 * @param totalPrice the total price of this sale cart
	 */
	public void setTotalPrice(double totalPrice);

	/**
	 * Returns the able of this sale cart.
	 *
	 * @return the able of this sale cart
	 */
	public boolean getAble();

	/**
	 * Returns <code>true</code> if this sale cart is able.
	 *
	 * @return <code>true</code> if this sale cart is able; <code>false</code> otherwise
	 */
	public boolean isAble();

	/**
	 * Sets whether this sale cart is able.
	 *
	 * @param able the able of this sale cart
	 */
	public void setAble(boolean able);

}