/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sales.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StockProductsList service. Represents a row in the &quot;SalesTaxe_StockProductsList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sales.model.impl.StockProductsListModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sales.model.impl.StockProductsListImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StockProductsList
 * @generated
 */
@ProviderType
public interface StockProductsListModel extends BaseModel<StockProductsList> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stock products list model instance should use the {@link StockProductsList} interface instead.
	 */

	/**
	 * Returns the primary key of this stock products list.
	 *
	 * @return the primary key of this stock products list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stock products list.
	 *
	 * @param primaryKey the primary key of this stock products list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this stock products list.
	 *
	 * @return the product ID of this stock products list
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this stock products list.
	 *
	 * @param productId the product ID of this stock products list
	 */
	public void setProductId(long productId);

	/**
	 * Returns the stock ID of this stock products list.
	 *
	 * @return the stock ID of this stock products list
	 */
	public long getStockId();

	/**
	 * Sets the stock ID of this stock products list.
	 *
	 * @param StockId the stock ID of this stock products list
	 */
	public void setStockId(long StockId);

}